### PR TITLE
Add the kinto-amo plugin.

### PR DESCRIPTION
**Pull request by Natim**
r? @leplatrem

### CODE REVIEW

**Comment by leplatrem** [comment]
r- :)

I'd like to kinto-dist as a mozilla agnostic package (as much as possible). kinto-amo is specific to mozilla, and specific to the amo deployment. I suggest that we put it in the puppet job instead

**Comment by Natim** [comment]
> kinto-amo is specific to mozilla, and specific to the amo deployment.

I totally agree.

> I'd like to kinto-dist as a mozilla agnostic package (as much as possible).

That's a discussion we need to have. Maybe we should rename the project to mozilla-services/kinto-settings

Today we use it for this deploy only but if we were to use it for something else we should probably not add kinto-amo.

**Comment by tarekziade** [comment]
> "specific to the amo deployment" 

It's "specific to the mozilla deployment." in our case, and one good question would be: does the community needs kinto-dist ?

> I'd like to kinto-dist as a mozilla agnostic package (as much as possible)

I'd be tempted to move kinto-dist to mozilla-services, it's not clear what is the use case to keep it mozilla-agnostic.

> I suggest that we put it in the puppet job instead

I don't think it's possible if we change some Python code. And if we're moving some dist logic from kinto-dist to puppet, we lost the initial goal we had, which is to provide ops with a kinto distribution ready to be used for all deployments

**Comment by leplatrem** [comment]
> rename the project to mozilla-services/kinto-settings

yes why not move this to mozilla specific indeed (kinto-dist is a better name though)

> does the community needs kinto-dist ?

the only use-case I had in mind was to use it as a base for distro packaging (e.g debian)

**Comment by Natim** [comment]
@leplatrem What do I need to do to get your r+? shall I make the org move?

**Comment by leplatrem** [comment]
Sorry for not replying before (got lost in notifications).
Yes, if we move to mozilla-services I definitely agree on adding this here.

**Pull request merged**
